/*
BladeburnerActionEnumType				Action types of Bladeburner
BladeburnerActionName
BladeburnerActionType
BladeburnerActionTypeForSleeve
BladeburnerBlackOpName
BladeburnerBlackOpNameEnumType			Black Operation names of Bladeburner
BladeburnerContractName
BladeburnerContractNameEnumType			Contract names of Bladeburner
BladeburnerGeneralActionName
BladeburnerGeneralActionNameEnumType	General action names of Bladeburner
BladeburnerOperationName
BladeburnerOperationNameEnumType		Operation names of Bladeburner
BladeburnerSkillName
BladeburnerSkillNameEnumType			Skill names type of Bladeburner

*/