/*
CorpEmployeePosition
CorpIndustryName
CorpMaterialName
CorpResearchName
CorpSmartSupplyOption
CorpStateName
CorpUnlockName
CorpUpgradeName

CreatingCorporationCheckResult
CreatingCorporationCheckResultEnumType
*/